ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS platform TEXT NOT NULL DEFAULT 'desktop';
ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS app_version TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
