import {
  ArrowDown,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  Ban,
  Bell,
  Box,
  Boxes,
  Building2,
  CalendarDays,
  ChartLine,
  ChartNoAxesColumnIncreasing,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock3,
  Cloud,
  CloudDownload,
  Code2,
  Coins,
  Cookie,
  Copy,
  Cuboid,
  Database,
  ExternalLink,
  FileInput,
  Flame,
  FolderOpen,
  FolderTree,
  Gauge,
  GitBranch,
  GripHorizontal,
  Inbox,
  KeyRound,
  Laptop,
  Layers3,
  Link2,
  List,
  LoaderCircle,
  LogIn,
  Monitor,
  Moon,
  Pencil,
  PieChart,
  PlugZap,
  Plus,
  RefreshCw,
  RotateCcw,
  Scale,
  Search,
  Server,
  Settings,
  ShieldHalf,
  SlidersHorizontal,
  SquarePen,
  Sun,
  Tag,
  Tags,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  WalletCards,
  X,
  Zap,
  type LucideIcon
} from 'lucide-react'
import clsx from 'clsx'

const ICONS: Record<string, LucideIcon> = {
  'fa-arrow-down': ArrowDown,
  'fa-arrow-right': ArrowRight,
  'fa-arrow-right-arrow-left': ArrowRightLeft,
  'fa-arrow-right-to-line': LogIn,
  'fa-arrows-rotate': RefreshCw,
  'fa-arrow-trend-up': TrendingUp,
  'fa-arrow-up': ArrowUp,
  'fa-arrow-up-from-bracket': Upload,
  'fa-arrow-up-right-from-square': ExternalLink,
  'fa-ban': Ban,
  'fa-bell': Bell,
  'fa-bolt': Zap,
  'fa-box': Box,
  'fa-building': Building2,
  'fa-calendar-week': CalendarDays,
  'fa-chart-line': ChartLine,
  'fa-chart-pie': PieChart,
  'fa-chart-simple': ChartNoAxesColumnIncreasing,
  'fa-chevron-left': ChevronLeft,
  'fa-chevron-right': ChevronRight,
  'fa-chevron-up': ChevronUp,
  'fa-circle-check': CircleCheck,
  'fa-circle-exclamation': CircleAlert,
  'fa-circle-notch': LoaderCircle,
  'fa-clock': Clock3,
  'fa-clock-rotate-left': RotateCcw,
  'fa-cloud': Cloud,
  'fa-cloud-arrow-down': CloudDownload,
  'fa-code': Code2,
  'fa-code-branch': GitBranch,
  'fa-coins': Coins,
  'fa-cookie-bite': Cookie,
  'fa-copy': Copy,
  'fa-cube': Cuboid,
  'fa-cubes': Boxes,
  'fa-cubes-stacked': Boxes,
  'fa-database': Database,
  'fa-file-import': FileInput,
  'fa-fire': Flame,
  'fa-folder-open': FolderOpen,
  'fa-folder-tree': FolderTree,
  'fa-gauge-high': Gauge,
  'fa-gear': Settings,
  'fa-grip-lines': GripHorizontal,
  'fa-inbox': Inbox,
  'fa-key': KeyRound,
  'fa-laptop': Laptop,
  'fa-layer-group': Layers3,
  'fa-link': Link2,
  'fa-list-ul': List,
  'fa-display': Monitor,
  'fa-magnifying-glass': Search,
  'fa-pen': Pencil,
  'fa-pen-to-square': SquarePen,
  'fa-plug': PlugZap,
  'fa-plus': Plus,
  'fa-rotate-left': RotateCcw,
  'fa-scale-balanced': Scale,
  'fa-server': Server,
  'fa-shield-halved': ShieldHalf,
  'fa-sliders': SlidersHorizontal,
  'fa-spinner': LoaderCircle,
  'fa-moon': Moon,
  'fa-sun': Sun,
  'fa-tag': Tag,
  'fa-tags': Tags,
  'fa-trash-can': Trash2,
  'fa-triangle-exclamation': TriangleAlert,
  'fa-wallet': WalletCards,
  'fa-xmark': X
}

export function Icon({
  name,
  className,
  size = '1em',
  strokeWidth = 1.75,
  ...props
}: {
  name: string
  className?: string
  size?: number | string
  strokeWidth?: number
} & Omit<React.ComponentPropsWithoutRef<'svg'>, 'name'>) {
  const Component = ICONS[name] ?? CircleHelp
  return (
    <Component
      className={clsx('moon-icon', className)}
      width={size}
      height={size}
      strokeWidth={strokeWidth}
      aria-hidden="true"
      {...props}
    />
  )
}
