/**
 * IPC 通道名常量:集中定义渲染进程与主进程之间所有 invoke/handle 通道字符串。
 * 使用 `as const` 以获得字面量类型,避免通道名拼写不一致。
 * (glm-5.2)
 */
export const IPC = {
  keysList: 'keys:list',
  keysAdd: 'keys:add',
  keysUpdate: 'keys:update',
  keysDelete: 'keys:delete',
  keysTest: 'keys:test',
  keysSetUsageQuery: 'keys:set-usage-query',
  keysImportFromCLI: 'keys:import-from-cli',
  usageRefreshAll: 'usage:refresh-all',
  codexUsage: 'codex:usage',
  syncStatus: 'sync:status',
  syncPreview: 'sync:preview',
  syncNow: 'sync:now',
  syncOnline: 'sync:online',
  syncLogin: 'sync:login',
  syncDevices: 'sync:devices',
  syncRevokeDevice: 'sync:revoke-device',
  usageGetDashboard: 'usage:get-dashboard',
  usageGetLogs: 'usage:get-logs',
  usageGetLogsPage: 'usage:get-logs-page',
  usageGetTotalSpend: 'usage:get-total-spend',
  usageGetModelSpend: 'usage:get-model-spend',
  usageGetKeySpend: 'usage:get-key-spend',
  balanceListLatest: 'balance:list-latest',
  providersList: 'providers:list',
  providersCatalog: 'providers:catalog',
  logDiscover: 'log:discover',
  logLocations: 'log:locations',
  logSync: 'log:sync',
  logSyncProgress: 'subscribe:log-sync-progress',
  logSyncDone: 'subscribe:log-sync-done',
  logDetectCodexKey: 'log:detect-codex-key',
  logDetectClaudeKey: 'log:detect-claude-key',
  logOpenFolder: 'log:open-folder',
  pricingList: 'pricing:list',
  pricingSet: 'pricing:set',
  pricingRestore: 'pricing:restore',
  pricingCatalog: 'pricing:catalog',
  pricingCatalogPreview: 'pricing:catalog-preview',
  pricingCatalogApply: 'pricing:catalog-apply',
  pricingHistory: 'pricing:history',
  pricingExchangePolicy: 'pricing:exchange-policy',
  pricingExchangePolicySet: 'pricing:exchange-policy-set',
  pricingCatalogStatus: 'pricing:catalog-status',
  pricingCatalogAutoUpdate: 'pricing:catalog-auto-update',
  pricingCatalogApprovalRequired: 'pricing:catalog-approval-required',
  pricingCnyRate: 'pricing:cny-rate',
  appUpdateGetStatus: 'app-update:get-status',
  appUpdateCheck: 'app-update:check',
  appUpdateStatusChanged: 'subscribe:app-update-status',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsChooseDirectory: 'settings:choose-directory',
  alertsList: 'alerts:list',
  alertsAdd: 'alerts:add',
  alertsToggle: 'alerts:toggle',
  alertsDelete: 'alerts:delete'
} as const
